use crate::core::objects::Offset;

#[derive(Debug)]
pub enum ErrorDitheringEnum {
    FloydSteinberg,
    JarvisJudiceNinke,
    Stucki,
    Burkes,
    Sierra,
    SierraLite,
    Atkinson,
}

impl ErrorDitheringEnum {
    pub fn distribution(&self) -> &'static [Offset] {
        match self {
            ErrorDitheringEnum::FloydSteinberg => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 7,
                    dividend: 16,
                    weight: 7.0 / 16.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 5,
                    dividend: 16,
                    weight: 5.0 / 16.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 3,
                    dividend: 16,
                    weight: 3.0 / 16.0,
                },
                Offset {
                    x: -1,
                    y: 1,
                    divisor: 5,
                    dividend: 16,
                    weight: 5.0 / 16.0,
                },
            ],
            ErrorDitheringEnum::JarvisJudiceNinke => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 7,
                    dividend: 48,
                    weight: 7.0 / 48.0,
                },
                Offset {
                    x: 2,
                    y: 0,
                    divisor: 5,
                    dividend: 48,
                    weight: 5.0 / 48.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 3,
                    dividend: 48,
                    weight: 3.0 / 48.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 5,
                    dividend: 48,
                    weight: 5.0 / 48.0,
                },
                Offset {
                    x: 2,
                    y: 1,
                    divisor: 3,
                    dividend: 48,
                    weight: 3.0 / 48.0,
                },
                Offset {
                    x: 0,
                    y: 2,
                    divisor: 1,
                    dividend: 48,
                    weight: 1.0 / 48.0,
                },
                Offset {
                    x: 1,
                    y: 2,
                    divisor: 3,
                    dividend: 48,
                    weight: 3.0 / 48.0,
                },
                Offset {
                    x: 2,
                    y: 2,
                    divisor: 1,
                    dividend: 48,
                    weight: 1.0 / 48.0,
                },
            ],
            ErrorDitheringEnum::Stucki => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 8,
                    dividend: 42,
                    weight: 8.0 / 42.0,
                },
                Offset {
                    x: 2,
                    y: 0,
                    divisor: 4,
                    dividend: 42,
                    weight: 4.0 / 42.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 2,
                    dividend: 42,
                    weight: 2.0 / 42.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 4,
                    dividend: 42,
                    weight: 4.0 / 42.0,
                },
                Offset {
                    x: 2,
                    y: 1,
                    divisor: 2,
                    dividend: 42,
                    weight: 2.0 / 42.0,
                },
                Offset {
                    x: 0,
                    y: 2,
                    divisor: 1,
                    dividend: 42,
                    weight: 1.0 / 42.0,
                },
                Offset {
                    x: 1,
                    y: 2,
                    divisor: 2,
                    dividend: 42,
                    weight: 2.0 / 42.0,
                },
                Offset {
                    x: 2,
                    y: 2,
                    divisor: 1,
                    dividend: 42,
                    weight: 1.0 / 42.0,
                },
            ],
            ErrorDitheringEnum::Burkes => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 8,
                    dividend: 32,
                    weight: 8.0 / 32.0,
                },
                Offset {
                    x: 2,
                    y: 0,
                    divisor: 4,
                    dividend: 32,
                    weight: 4.0 / 32.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 2,
                    dividend: 32,
                    weight: 2.0 / 32.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 4,
                    dividend: 32,
                    weight: 4.0 / 32.0,
                },
                Offset {
                    x: 2,
                    y: 1,
                    divisor: 2,
                    dividend: 32,
                    weight: 2.0 / 32.0,
                },
                Offset {
                    x: 0,
                    y: 2,
                    divisor: 1,
                    dividend: 32,
                    weight: 1.0 / 32.0,
                },
                Offset {
                    x: 1,
                    y: 2,
                    divisor: 2,
                    dividend: 32,
                    weight: 2.0 / 32.0,
                },
                Offset {
                    x: 2,
                    y: 2,
                    divisor: 1,
                    dividend: 32,
                    weight: 1.0 / 32.0,
                },
            ],
            ErrorDitheringEnum::Sierra => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 5,
                    dividend: 32,
                    weight: 5.0 / 32.0,
                },
                Offset {
                    x: 2,
                    y: 0,
                    divisor: 3,
                    dividend: 32,
                    weight: 3.0 / 32.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 2,
                    dividend: 32,
                    weight: 2.0 / 32.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 4,
                    dividend: 32,
                    weight: 4.0 / 32.0,
                },
                Offset {
                    x: 2,
                    y: 1,
                    divisor: 3,
                    dividend: 32,
                    weight: 3.0 / 32.0,
                },
                Offset {
                    x: 0,
                    y: 2,
                    divisor: 1,
                    dividend: 32,
                    weight: 1.0 / 32.0,
                },
                Offset {
                    x: 1,
                    y: 2,
                    divisor: 2,
                    dividend: 32,
                    weight: 2.0 / 32.0,
                },
                Offset {
                    x: 2,
                    y: 2,
                    divisor: 1,
                    dividend: 32,
                    weight: 1.0 / 32.0,
                },
            ],
            ErrorDitheringEnum::SierraLite => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 5,
                    dividend: 16,
                    weight: 5.0 / 16.0,
                },
                Offset {
                    x: 2,
                    y: 0,
                    divisor: 3,
                    dividend: 16,
                    weight: 3.0 / 16.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 2,
                    dividend: 16,
                    weight: 2.0 / 16.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 2,
                    dividend: 16,
                    weight: 2.0 / 16.0,
                },
                Offset {
                    x: 0,
                    y: 2,
                    divisor: 1,
                    dividend: 16,
                    weight: 1.0 / 16.0,
                },
            ],
            ErrorDitheringEnum::Atkinson => &[
                Offset {
                    x: 1,
                    y: 0,
                    divisor: 1,
                    dividend: 8,
                    weight: 1.0 / 8.0,
                },
                Offset {
                    x: 2,
                    y: 0,
                    divisor: 1,
                    dividend: 8,
                    weight: 1.0 / 8.0,
                },
                Offset {
                    x: 0,
                    y: 1,
                    divisor: 1,
                    dividend: 8,
                    weight: 1.0 / 8.0,
                },
                Offset {
                    x: 1,
                    y: 1,
                    divisor: 1,
                    dividend: 8,
                    weight: 1.0 / 8.0,
                },
                Offset {
                    x: 0,
                    y: 2,
                    divisor: 1,
                    dividend: 8,
                    weight: 1.0 / 8.0,
                },
                Offset {
                    x: 1,
                    y: 2,
                    divisor: 1,
                    dividend: 8,
                    weight: 1.0 / 8.0,
                },
            ],
        }
    }
}
